repos:
  - repo: local
    hooks:
      - id: ruff-format
        name: ruff-format
        entry: uv run ruff format
        language: system
        types: [python]
        args: []
        stages: [pre-push]
      - id: ruff-check
        name: ruff-check
        entry: uv run ruff check
        language: system
        types: [python]
        args: [--fix]
        stages: [pre-push]
      - id: pytest
        name: pytest
        entry: uv run pytest packages/un-datacommons-mcp/tests
        pass_filenames: False
        files: ^packages/un-datacommons-mcp/
        language: system
        stages: [pre-push]
